### ISSUE TITLE
Error in MakeExcel wanneer csv_resultaten al bestaan

### ISSUE THREAD

**Issue by pieterseinen** [ggdatascience/GGData_tabellenboek#10]
MakeExcel() kan niet uitgevoerd worden wanneer de cvs resultaten al bestaan. Mogelijk wordt er bij het uitrekenen van de csv_resultaten een object aangemaakt / aangepast waar MakeExcel() van afhankelijk is.

```
Eerdere resultaten aangetroffen vanuit deze configuratie (configuratie.xlsx). Berekening wordt overgeslagen. Indien er nieuwe data is toegevoegd, verwijder dan de bestanden uit de map resultaten_csv.
Tabellenboek voor Gemeente 1 wordt gemaakt.
output[data.var$val[data.var$col.index == j], j] <- data.var$perc.weighted[data.var$col.index == : 

number of items to replace is not a multiple of replacement length
```

**Comment by aartdijkstra** [comment]
Dit bleek een probleem te zijn met een antwoordwaarde van 0. Als dit een getal is dan snapt R het niet; rij 0 bestaat natuurlijk nooit. as.character() omheen gezet, nu werkt het wel.
