### ISSUE TITLE
Foutief overschrijven ewGGD

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#12]
Ergens in de code wordt kolom ewGGD overschreven of verwijderd, ik kan niet zo goed vinden waar. Vervolgens krijg ik een error bij berekeningen bij 

`data.tmp = data[,vars]`

Omdat want laatste element van vars is "ewGGD" en die kolom bestaat niet (meer) in data. Maar ik heb het idee dat die nu in vars[13] staat want daar is de label "Gewicht alleen GGD respondenten".

Verdere info:
- Ik heb in de configuratie alleen ewGGD als gewicht opgegeven, nog niks van ewGGDCBS oid.
- Vars is dit (zitten dus ook NA in):
![image](https://user-images.githubusercontent.com/127401018/231165849-eea0c83c-a8bb-4a25-9042-7c3c48875043.png)
- als datasets heb ik alleen GGD Twente en NL totaal, geen eerdere jaren oid. Kan je configuratie sturen als dat helpt.
- De fout treedt meteen bij de eerste var op

**Comment by HenkBroekhuizen** [comment]
Dit was denk ik mijn fout omdat ik ewGGD in indeling_rijen ook had staan. Als de boel weer draait (zie memory issue #13) zal ik kijken of dit klopt en zonodig dit issue sluiten.

**Comment by aartdijkstra** [comment]
In principe zou er geen enkele kolom overschreven moeten worden. Er worden extra kolommen aangemaakt voor gewichten, strata en datasets, maar die zijn zo genoemd dat ze nooit iets zullen overschrijven. (Overbodig voor nu, maar for future reference.)
