### ISSUE TITLE
Crash to desktop; memory issue?

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#13]
Ik krijg af en toe een crash to desktop van Rstudio zonder foutmelding. Mijn gevoel is dat het iets te maken heeft met memory usage. Als ik de data van Twente en NL inlaadt gebruikt R namelijk >6gb aan werkgeheugen al. Dit is waarschijnlijk lastig op te lossen snel, als dat het is. Zou het kunnen zijn dat het data-type wat we in R gebruiken, het object wat uit read_sav rolt, veel ruimte inneemt? Dan zouden we kunnen overwegen dat te vervangen. Er zijn wel packages in R om met grotere databestanden te werken.

**Comment by HenkBroekhuizen** [comment]
`object.size(data)` geeft 109 mb, dat is niet zoveel. Kan het zijn dat een operatie op de data de boel opblaast?

**Comment by aartdijkstra** [comment]
Ik kan het zowel op mijn fragiele GGD-laptop (8 GB) en mijn thuismonster (32 GB) niet reproduceren. Ik kom inderdaad ook uit op een 6 á 7 GB gebruikt door R.

**Comment by HenkBroekhuizen** [comment]
Ik heb dit nu ook niet meer, wellicht dat ik eerder iets fout deed. Ik sluit de issue nu.
