### ISSUE TITLE
Error bij svychisq in tbl_GetTableRow

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#15]
Ik krijg de error

`Error in sum(sapply(stratvars, function(m) !any(is.na(m)))) : 
  invalid 'type' (list) of argument`

op regel 207 bij deze code:
`test = svychisq(formula=as.formula(paste0("~dummy.", var, ".", answer, "+", col.design$crossing[i])), design=design.subset)`

Eerste argument naar svychisq is `~dummy.AGHHA209.1 + AGGSA202
<environment: 0x0000025f581ff5a0>`

Design is gewoon
`Stratified Independent Sampling design (with replacement)
design.subset = subset(design, eval(parse(text=selection)))`

Onder liggende data uit design is
![image](https://user-images.githubusercontent.com/127401018/232031402-09d37eb0-f059-42e0-ae9a-bf4320e4eaec.png)

**Comment by aartdijkstra** [comment]
Inderdaad, die had ik ook net gespot dankzij Hanna. Fix staat erin!

**Comment by HenkBroekhuizen** [comment]
:D

**Comment by aartdijkstra** [comment]
Na flink zoeken kwamen Henk en ik erachter dat dit komt door het missen van strata. Er is nu een foutmelding ingebouwd voor wanneer dit weer voorkomt.
