### ISSUE TITLE
Error in tbl_MakeExcel bij lege resultaten

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#16]
Rond regel 209 en rond regel 220 van tbl_MakeExcel staat code
`data.tmp$col.index = j
            data.var = bind_rows(data.var, data.tmp)`
Dit geeft een foutmelding als het zojuist gemaakt data.tmp object leeg is. Hier een if omheen zetten verhelpt het probleem:
`if(nrow(data.tmp) > 0){
            data.tmp$col.index = j
            data.var = bind_rows(data.var, data.tmp)
          }`
Maar misschien alleen maar het symptoom van het probleem, want waarom is data.tmp leeg? daar ben ik nog niet helemaal achter.

**Comment by HenkBroekhuizen** [comment]
Deze bug is opgelost @aartdijkstra . Fout zat erin dat ik de NL dataset in R naar Twente alleen had gefilterd en daarna weer als .SAV opgeslagen had. Bij die vertaling gaat eea mis wb missings. Door de split met spss te doen gaat het wel goed. Zijn er checks in te bouwen voor deze fout? variabelen hebben in hun labels attribute wel een 'onbekend' label, als die value nog in de data zit is er iets mis. Eerder had ik onderstaande functie gemaakt misschien heb je daar wat aan: 

AutomaticNaOnUnknown <- function(
    data.in,
    keywords.in = c("onbekend"),
    verbose.in
){
  ConditionalMessage(paste("Setting to NA these labels: ", keywords.in), verbose.in >= 2)
  
  SetToNaBasedOnLabels <- function(x, keywords){
    l <- attr(x, "labels")
    if(is.null(l)){
      return(x) # hier nog loggen ofzo?
    }
    to_remove_keys <- grepl(paste0(keywords, collapse = "|"), names(l), ignore.case = T)
    to_remove <- l[to_remove_keys]
    if(length(to_remove) > 0){
      for(k in to_remove){
        x <- dplyr::na_if(x, k)  
      }
    }
    return(x)
  }

  for(j in 1:ncol(data.in)){
    ConditionalMessage(colnames(data.in)[j], verbose.in >= 3)
    data.in[[j]] <- SetToNaBasedOnLabels(data.in[[j]], keywords.in)
  }
  
  return(data.in)
}

**Comment by aartdijkstra** [comment]
Die if was inderdaad nog afwezig in de code. (Zie ook de foutmelding van Hanna, zelfde probleem.) data.tmp kan ook leeg zijn als er een vraag is die in een eerder jaar niet gesteld is. Ik vraag me wel af waarom dit bij mij nooit foutmeldingen gaf, want ik heb ook flink wat variabelen die niet in alle jaren zitten...
