### ISSUE TITLE
Voorstel nieuwe versie NA.identical

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#17]
Deze functie werkte (voor zover ik 'm snapte) niet als er NA's waren in vect. Voorstel (ik heb een else if toegevoegd):

```
NA.identical = function (vect, cmp) {
  if (is.na(cmp)) {
    return(is.na(vect))
  } else if(sum(is.na(vect)) > 0){
    out <- !is.na(vect) & vect == cmp
  } else {
    return(vect == cmp)
  }
}
```

**Comment by aartdijkstra** [comment]
Als het goed is wordt dit al ondervangen door de which() waarin de NA.identical()s gewrapt zijn. Als we een willekeurige dataset nemen met 5x 1, 2x NA, 3x 2:
![afbeelding](https://user-images.githubusercontent.com/125073330/232900457-cd43838e-3536-4d0b-b5b8-dd0680daf43f.png)
