### ISSUE TITLE
Verwerking parallel maken

### ISSUE THREAD

**Issue by aartdijkstra** [ggdatascience/GGData_tabellenboek#2]

**Comment by HenkBroekhuizen** [comment]
ll380-390 tbl_maken: voorstel te vervangen door (met parallel):

> if(do.parallel){ # TODO: toevoegen als optie in config
>   nodes <- detectCores()
>   cl <- makeCluster(nodes)
>   registerDoParallel(cl, nodes)
> }
> 
> out <- alply(
>   .data = varlist,
>   .margins = 1,
>   .fun = PrepdataForSurveyAndGetTableRow,
>   data.in = data,
>   kolom_opbouw.in = kolom_opbouw,
>   subsetmatches.in = subsetmatches,
>   .parallel = do.parallel,
>   .paropts = list(
>     .packages = c("survey", "dplyr", "haven")
>   ),
>   .progress = progress_time()
> )
> 
> results <- out %>% reduce(.f = bind_rows)
> 
> if(do.parallel){
>   stopCluster(cl)
> }

en dan deze functie ergens laten inladen:

> PrepdataForSurveyAndGetTableRow = function(
>   var,
>   data.in,
>   kolom_opbouw.in,
>   subsetmatches.in
> ){
>   vars = c(var, kolom_opbouw.in$crossing, kolom_opbouw.in$subset, colnames(data.in)[str_starts(colnames(data.in), "dummy._col")],
>            colnames(data.in)[str_starts(colnames(data.in), paste0("dummy.", var))], "superstrata", "superweegfactor")
>   vars = unique(vars[!is.na(vars)])
>   data.in.tmp = data.in[,vars]
>   design = svydesign(ids=~1, strata=data.tmp$superstrata, weights=data.in.tmp$superweegfactor, data=data.in.tmp)
>   return(GetTableRow(var, design, F, kolom_opbouw.in, subsetmatches.in))
> }

dit is nog wel ongetest en neemt aan dat tbl_GetTableRow geen aannames maakt over variabelen en functies die in het environment staan, anders moeten die nog expliciet meegegeven worden aan alply.

**Comment by aartdijkstra** [comment]
Hiermee vermeervoudig (afhankelijk van de processor) je dan wel het gebruikte geheugen. Iedere core moet de hele dataset overnemen. Kunnen we hier nog een slimme truc voor bedenken?

**Comment by HenkBroekhuizen** [comment]
> Hiermee vermeervoudig (afhankelijk van de processor) je dan wel het gebruikte geheugen. Iedere core moet de hele dataset overnemen. Kunnen we hier nog een slimme truc voor bedenken?

Bij JV was dit geen probleem, maar bij VO wel, dat zijn echt grote bestanden. Er zijn vast oplossingen, dat de hele dataset niet in de R sessie ingeladen hoeft, maar dat die on disk blijft en je gewoon een specifieke deel ophaalt dmv een query oid. Maar dat is nu nog even zoeken en volgens mij best een hele onderneming...

**Comment by aartdijkstra** [comment]
Dan lijkt het me praktischer om voor nu multithreading even te laten voor wat het is en dit na VO een keer uit te zoeken, zeker gezien. #13

**Comment by HenkBroekhuizen** [comment]
Yes dan sluit ik deze voor nu. Terug naar de backlog!
