### ISSUE TITLE
Aantal respondenten bovenaan klopt niet

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#21]
Via Hanna Verweij GGD HM:
 
We hebben in Alphen xxx respondenten (dus dat kan kloppen!) maar in totaal in HM xxx, dus dat lijkt hier een soort verdubbeld te zijn. 

We hebben in de configuratie bij ‘onderdelen’ twee rijen ingevuld, één keer gecrossed voor de gemeente en één keer voor de totale regio:
![image](https://user-images.githubusercontent.com/127401018/232798196-151117e7-c77a-449b-ab86-a8a230b7295a.png)
 
Voor de regio-aantallen zijn ze ongeveer verdubbeld, zowel bij de crossings als bij het totaal:

[plaatje]

Ik zag dat hij in tbl_MakeExcel.R wel netjes de (sum van) unweighted N neemt, maar blijkbaar staan die HM-regels er 2x in ofzo? Ik weet niet of het een foutje is in het script of dat ik het niet zo moet doen in de configuratie, maar dan zou dat misschien nog iets duidelijker mogen in de handleiding.

**Comment by aartdijkstra** [comment]
Aangezien ik door het samenvoegen van de datasets niet gewoon nrow(data) kan doen heb ik een (ietwat smerig) trucje toegepast om de aantallen te krijgen. Hierbij deed ik bij kolommen met subset gewoon een select if subset == blabla, en bij kolommen zonder subset select if (alles behalve de subset), waardoor in geval twee de meetpunten van geval één meegenomen worden. Dat is natuurlijk niet hoe het hoort te gaan; die tweede moet selecteren op subset (bestaat niet). Nu aangepast!
