### ISSUE TITLE
Variabelen kunnen opnemen die aan één (sub)groep gesteld is

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#22]
Via Hanna Verweij GGD HM:

Wij willen in ons tabellenboek variabelen opnemen die er voor de ene groep (18-64 jaar) wel zijn maar voor de andere groep niet. De vorige keer zag dit er zo uit:

[plaatje]

Wij hebben dat geprobeerd met het script en het uitdraaien van de resultaten (csv’s) gaat goed, maar het maken van het tabellenboek niet:

![image](https://user-images.githubusercontent.com/127401018/232798934-72a2b499-477b-4e5f-ae45-9ac88af4f17d.png)

met traceback naar r. 209 van tbl_MakeExcel (data.tmp$col.index = j)
Ik snap wel waarom dat gebeurt, want in de resultaten staat ipv de resultaten voor 2 groepen (waarvan er één dus leeg of missing moet zijn) de resultaten voor die ene groep twee keer:

[plaatje]

Is hier een oplossing voor (te bedenken)? Bij de gezondheidsmonitor VO zijn er behoorlijk wat vragen gesteld die voor maar 1 doelgroep golden (bijv. kwetsbaarheid ouderen, AOW, wekelijkse activiteiten, functiebeperkingen, etc. etc.) dus iedere GGD die het tabellenboek op leeftijd wil splitsen zal hier tegenaan lopen.

**Comment by aartdijkstra** [comment]
Aangezien ik door het samenvoegen van de datasets niet gewoon nrow(data) kan doen heb ik een (ietwat smerig) trucje toegepast om de aantallen te krijgen. Hierbij deed ik bij kolommen met subset gewoon een select if subset == blabla, en bij kolommen zonder subset select if (alles behalve de subset), waardoor in geval twee de meetpunten van geval één meegenomen worden. Dat is natuurlijk niet hoe het hoort te gaan; die tweede moet selecteren op subset (bestaat niet). Nu aangepast!
