### ISSUE TITLE
Dubbele respondentaantallen als een var tweemaal voorkomt in indelingen_rijen

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#25]
Onze totalen klopten niet, dit kwam omdat we een variabele tweemaal in indeling rijen hadden. Oplossingsrichtingen:

1. waarschuwing in tbl_maken regel 89 aanpassen om dit te zeggen
2. waarschuwing in tbl_maken regel 89 aanpassen naar een error
3. in tbl_MakeExcel corrigeren voor de dubbeling, bv controleren of waarden in 'val' dubbel voorkomen en dan aanpassen met iets als een aggregate

Ik ben zelf voor optie 2.

**Comment by aartdijkstra** [comment]
We zouden bij de berekening `group_by(var, val) %>% summarize(n=mean(n.unweighted, na.rm=T)` kunnen toevoegen, daardoor verdwijnt een dubbeling, of inderdaad gewoon een foutmelding. Is er een scenario te bedenken waarin een variabele twee keer zou moeten voorkomen in het tabellenboek?
