### ISSUE TITLE
Aantal respondenten boven tabel klopt niet als je missings hebt in variabelen

### ISSUE THREAD

**Issue by mariellederijk** [ggdatascience/GGData_tabellenboek#26]
Het aantal respondenten wat wordt weergeven boven de tabel is nu gebaseerd op de grootste aantal respondenten van een variabele in uit de variabelelijst/indeling_indeling rijen. Echter, deze komt niet overeen met de daadwerkelijke aantallen. Als je Lftcat5 toevoegt dan heb je wel de daadwerkelijke aantallen, maar kun je geen crossings naar deze leeftijdgroepindeling doen. (Error in dn[[2L]] : subscript out of bounds). Hoe kunnen we deze twee issues oplossen?

**Comment by aartdijkstra** [comment]
Dit is een iets lastiger puntje. De vraag is of het aantal moet slaan op het aantal antwoorden (daadwerkelijk ingevulde vragen) of het aantal respondenten ongeacht het antwoord (dus zeg maar het aantal rijen in SPSS). De laatste geeft misschien een vertekend beeld, omdat er dan geen rekening gehouden wordt met missende antwoorden. Andersom heeft de eerste het probleem dat een gebrek aan overlap niet direct zichtbaar is. We hadden daarom bij het maken gekozen voor het aantal antwoorden. In principe kan het aantal rijen vrij makkelijk worden toegevoegd met
`sum(data$dummy._col(getal))`

Het uitsluiten van een crossing in de lijst met variabelen is een bewuste keuze, omdat een kruistabel maken met zichzelf natuurlijk niet moet kunnen.

**Comment by mariellederijk** [comment]
Dankje Aart, waar in syntax tbl_MakeExcel kan dit het best geplaatst worden/ ter vervanging van welke regels?

**Comment by aartdijkstra** [comment]
In tbl_MakeExcel.R, regels 180:215 worden de aantallen berekend en ingevoegd. Je zou daar de code in de for kunnen vervangen door output[j] = sum(data$dummy._col(getal)), dan krijg je het totale aantal rijen.
