### ISSUE TITLE
Inherited (parts of) configuration

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#28]
Voor de rapportage draaien we een groot aantal tabellenboeken. Voor elk type is een configuratie Excel. Vaak zit daar overlap tussen. Bijvoorbeeld het tabblad 'indeling' rijen is bij veel configuraties hetzelfde, of de dataset tab, of de introtekst. Als hier veranderingen inkomen, bv een var die we overal erbij willen of tekstuele verandering aan de introtekst, moeten we dit overal handmatig aanpassen.

Het ons helpen als er een 'inherit' feature was die als volgt (oid) werkt:

1. je laat een tab leeg en zet alleen in cel a1 iets: namelijk INHERIT:<path>.
2. bij het inladen van de config haalt het script dan niet de inhoud van dat tabblad op, maar de inhoud van dat tabblad in de configuratie die in <path> te vinden is.

**Comment by aartdijkstra** [comment]
Eerste versie toegevoegd in de laatste commit: [hier](https://github.com/ggdatascience/GGData_tabellenboek/commit/f235b72f96bb38bd73f055a4ac749f68606346a9)
