### ISSUE TITLE
Weergave in Excel

### ISSUE THREAD

**Issue by aartdijkstra** [ggdatascience/GGData_tabellenboek#3]

**Comment by HenkBroekhuizen** [comment]
ll380-390 in tbl_maken: voorstel te vervangen door (met parallel):

> if(do.parallel){ # TODO: toevoegen als optie in config
>   nodes <- detectCores()
>   cl <- makeCluster(nodes)
>   registerDoParallel(cl, nodes)
> }
> 
> out <- alply(
>   .data = varlist,
>   .margins = 1,
>   .fun = PrepdataForSurveyAndGetTableRow,
>   data.in = data,
>   kolom_opbouw.in = kolom_opbouw,
>   subsetmatches.in = subsetmatches,
>   .parallel = do.parallel,
>   .paropts = list(
>     .packages = c("survey", "dplyr", "haven")
>   ),
>   .progress = progress_time()
> )
> 
> results <- out %>% reduce(.f = bind_rows)
> 
> if(do.parallel){
>   stopCluster(cl)
> }

en dan deze functie ergens laten inladen:

> PrepdataForSurveyAndGetTableRow = function(
>   var,
>   data.in,
>   kolom_opbouw.in,
>   subsetmatches.in
> ){
>   vars = c(var, kolom_opbouw.in$crossing, kolom_opbouw.in$subset, colnames(data.in)[str_starts(colnames(data.in), "dummy._col")],
>            colnames(data.in)[str_starts(colnames(data.in), paste0("dummy.", var))], "superstrata", "superweegfactor")
>   vars = unique(vars[!is.na(vars)])
>   data.in.tmp = data.in[,vars]
>   design = svydesign(ids=~1, strata=data.tmp$superstrata, weights=data.in.tmp$superweegfactor, data=data.in.tmp)
>   return(GetTableRow(var, design, F, kolom_opbouw.in, subsetmatches.in))
> }

dit is nog wel ongetest en neemt aan dat tbl_GetTableRow geen aannames maakt over variabelen en functies die in het environment staan, anders moeten die nog expliciet meegegeven worden aan alply.
