### ISSUE TITLE
Error bij maken trendtabellen voor scholen jeugd

### ISSUE THREAD

**Issue by mariellederijk** [ggdatascience/GGData_tabellenboek#38]
![image](https://github.com/ggdatascience/GGData_tabellenboek/assets/133016706/6516f79e-46ad-40e6-b001-c37f673d2de5)

We krijgen bovenstaande error als we spss trendbestand inladen met schoolcode (numeric) als subset. Waar zit mogelijk de error?

**Comment by WillekeWijburg** [comment]
In aanvulling op de post van Marielle. Op het moment dat je bij de onderdelen niet bij de bovenste crossing op WAAR zet krijg ik de genoemde foutmelding. Als ik daar crossing op WAAR zet, werkt het wel. Maar ik wil alleen de totalen van de scholen van de verschillende jaren en dat werkt dus niet. Wat gaat er niet goed?

**Comment by aartdijkstra** [comment]
Ik heb de code even handmatig doorgelopen bij verschillende scenario's, en precies dit scenario stond er nog niet in. Als sign_toetsen op WAAR staat, maar er geen daadwerkelijke testkolom is aangegeven bij één van de onderdelen, wordt de variabele bij de kolomindeling niet goed verwerkt. Ik heb de ontbrekende code toegevoegd, zie ook commit [dc2a5b177f35879557fa2eb425aa504739c6bfbd](https://github.com/ggdatascience/GGData_tabellenboek/commit/dc2a5b177f35879557fa2eb425aa504739c6bfbd)

**Comment by WillekeWijburg** [comment]
Dank je Aart! Het werkt nu wel.
