### ISSUE TITLE
Significantie toetsen voor lokale vragen met NL uitzetten 

### ISSUE THREAD

**Issue by fleurlr** [ggdatascience/GGData_tabellenboek#42]
Hoi, wij zouden graag bij het uitdraaien van een tabellenboek willen uitzetten dat lokale vragen worden getoetst met NL totaal (en dus dikgedrukt worden in het tabellenboek), want die data ontbreekt in het landelijke bestand. Hoe kunnen we dit doen?

Als het goed is heeft Joanne of Henk deze vraag ook per mail gesteld maar zij zijn deze week beide afwezig dus hopelijk kunnen jullie ons helpen. 

![tab boek](https://github.com/ggdatascience/GGData_tabellenboek/assets/158479778/b8087595-e9a0-4940-a15f-43f4dbcb5bb7)

**Comment by aartdijkstra** [comment]
Het heeft even moeite gekost, maar er staat een fix online! Nu krijg je een waarschuwing als één van de kolommen leeg is, en wordt er geen significantie weergegeven.
