### ISSUE TITLE
Het regionale tabellenboek krijgt de naam 'Overzicht'

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/GGData_tabellenboek#44]
Het regionale tabellenboek van de GM Jeugd krijgt de naam Overzicht en ook in de totaal kolommen van de jaren staat er Overzicht. Wij hebben verschillende dingen geprobeerd , maar het nog niet kunnen oplossen.
Iemand een idee?

Bij een tabellenboek voor een gemeente lukt het wel met een naam van gemeenten, totaal regio etc.

**Comment by aartdijkstra** [comment]
Ik heb een extra variabele toegevoegd aan het tabblad opmaak waarmee dit ingesteld kan worden; naam_tabellenboek.

**Comment by SBorsboom** [comment]
Dank, dan ga ik het daarmee proberen

**Comment by SBorsboom** [comment]
Ik heb in het configuratie bestand wat aangepast en nu komt er wel uit wat we willen.
