### ISSUE TITLE
Er wordt geen tabellenboek geproduceerd na toevoegen subset

### ISSUE THREAD

**Issue by kdeklerk** [ggdatascience/GGData_tabellenboek#48]
Als ik het tbl_maken script run met in het configuratiebestand een subset gespecificeerd (tabblad 'onderdelen') krijg ik geen output. Het script houdt dan op na "Totale rekentijd 0.00 min voor 1 variabelen. Gemiddelde tijd per variabele was 0.2 sec (range 0.2 - 0.2)" / vóór "Digitoegankelijk tabellenboek wordt gemaakt". De variabele 'subsetmatches' bestaat wel en geeft ook het juiste resultaat. Ik heb verschillende variabelen als subset geprobeerd, zonder soelaas. Voor verdere trouble-shooting is mijn R kennis helaas (nog) te beperkt. 

Als ik het script run met in het configuratiebestand zonder subset gespecificeerd (tabblad 'onderdelen') krijg ik wel een tabellenboek als output. 

Zie ik iets over het hoofd? Alvast bedankt!

[configuratie_GMJ_nieuw.xlsx](https://github.com/ggdatascience/GGData_tabellenboek/files/15077372/configuratie_GMJ_nieuw.xlsx)

**Comment by aartdijkstra** [comment]
Met een dergelijke rekentijd wordt er duidelijk geen data verwerkt. Kan het zijn dat de variabele Status niet correct het databestand splitst? Dit kun je zien aan het (al dan niet) bestaan van dummies; als het goed is bestaan er variabelen in de vorm data$dummy._col1.s.(mogelijkheden van variabele Status). Zo niet, dan staat die variabele waarschijnlijk niet goed.

**Comment by kdeklerk** [comment]
Dank voor je reactie! Ik heb wel die dummies, dus dat gaat wel goed... Enig idee wat het dan zou kunnen zijn?
