### ISSUE TITLE
Kolombreedte digitoegankelijke HTML

### ISSUE THREAD

**Issue by hannekeputtenstein** [ggdatascience/GGData_tabellenboek#50]
In het configuratiebestand heb ik (naast wat andere opmaak dingen) de kolombreedte van de antwoorden (kolombreedte_antwoorden) en de kolombreedte van de crossing (kolombreedte) aangepast. De kolombreedte verandert wel mee in de Excel, maar niet in de HTML. Is het mogelijk om dit alsnog via het configuratiebestand aan te passen? Of kan dit alleen door het aanpassen van de HTML-code?

**Comment by aartdijkstra** [comment]
Klopt, de HTML-versie werkt daarin net iets anders. In theorie zouden we kunnen zeggen dat we kolombreedte en kolombreedte_antwoorden omrekenen naar een percentage (wat daar wordt verwacht), maar doordat de tekstverdeling binnen HTML anders is is het maar de vraag of dat de gewenste resultaten geeft. De makkelijkste oplossing is dit in de HTML-template aanpassen. Dit is gelukkig heel simpel; op regel 65 (width: 15%) wordt de breedte van de labels gedefinieerd, de rest schaalt automatisch mee.

**Comment by hannekeputtenstein** [comment]
Bedankt voor het antwoord. Ik heb geprobeerd het volgende stukje (regel 60) van de HTML-code via Notepad++ aan te passen: 
![image](https://github.com/ggdatascience/GGData_tabellenboek/assets/165783462/e1786feb-3fee-4957-b693-7c3c1df4f977)

Als voorbeeld heb ik de 15% naar 40% aangepast. Vervolgens heb ik het R-script opnieuw gerund, maar er lijkt niets veranderd te zijn. Zie ik nog iets over het hoofd?

**Comment by hannekeputtenstein** [comment]
Het aanpassen van het aantal pixels werkt, bedankt!
