### ISSUE TITLE
vraag kolombreedte html

### ISSUE THREAD

**Issue by xsusanx** [ggdatascience/GGData_tabellenboek#51]
We willen graag de eerste kolom van de HTML versie verbreden. Kan dit en zo ja hoe? De Excel versie veranderd wel als je in het tabblad opmaak iets aanpast, maar de HTML versie niet.

**Comment by aartdijkstra** [comment]
Dit kan zeker. De indeling in HTML is helaas net wat anders dan binnen Excel, waardoor deze niet in de configuratie te verwerken is. In de template (template_digitoegankelijk.html) vindt je op regel 51 deze code:
```
colgroup:first-of-type col:first-of-type {
  width: 15%;
}
``` 
Als je dat percentage aanpast zal de eerste kolom groter (of kleiner) worden.
