### ISSUE TITLE
Crossing bij specifieke variabelen uitzetten

### ISSUE THREAD

**Issue by hannekeputtenstein** [ggdatascience/GGData_tabellenboek#53]
Goedemiddag,

Ik ben bezig met gemeentelijke tabellenboeken voor de nieuwe Gezondheidsmonitor Jongvolwassenen 2024. Hierbij wil ik de resultaten van de meeste variabelen graag uitsplitsen op geslacht en leeftijd. Bij sommige variabelen zou ik de uitsplitsing liever weglaten, omdat we daar met een erg lage prevalentie en dus met kleine aantallen te maken hebben (denk bijvoorbeeld aan drugsgebruik). Is het ook mogelijk om de crossings bij bepaalde variabelen uit te zetten?

**Comment by aartdijkstra** [comment]
Toegevoegd! Je kunt een extra kolom aanmaken in het tabblad indeling_rijen: verberg_crossings. Als je hier iets invult zullen de crossings niet toegevoegd worden. (Zie ook de voorbeeldconfiguratie.)

**Comment by hannekeputtenstein** [comment]
Wat super, dankjewel!
