### ISSUE TITLE
Backward compatibility Excel configs

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#55]
Soms worden er nieuwe functionaliteiten aan het script toegevoegd waarvoor de instellingen in het configuratiebestand staan. Hierdoor werken oude configuratiebestanden niet meer omdat het script een kolom verwacht die er niet is. Kunnen we iets bedenken, of steeds inbouwen bij nieuwe features, dat het script bij een missende kolom uitgaat van de default waarde (met warning)? Alternatief is om met branches te gaan werken en voor elke nieuwe GM een merge te doen zodat iedereen de analyseperiode ingaat met het nieuwe config bestand. Maar dan gaat de vlotheid er ook wel een beetje uit. Wat denk jij @aartdijkstra ?

**Comment by aartdijkstra** [comment]
Ik heb tot nu toe bij iedere verandering sinds de eerste monitor waarin dit script gebruikt is extra logica toegevoegd om nieuwe opties te corrigeren in oude configuraties. (Zie ook regels ~130:~180 in tbl_maken.R.) Als 't goed is zouden oude configuraties dus gewoon moeten werken, met hier en daar een waarschuwing dat standaardwaarden worden aangenomen. Zijn er specifieke dingen waar 'ie nu op vastloopt?
