### ISSUE TITLE
Error uitvoeren script

### ISSUE THREAD

**Issue by NathalieKoene** [ggdatascience/GGData_tabellenboek#57]
Hoi, 
ik ben bezig met het maken van een tabellenboek voor de GM JV2024.
Ik heb een testbestand voor de configuratie met enkele indicatoren. Deze heb ik eigenlijk zonder problemen gerund. Op basis van hoe de tabel er uitzag heb ik nog wat aanpassingen gedaan in de configuratie.

Nu ik het script opnieuw wil runnen, krijg ik onderstaande error:

[DEBUG] Datasets gecombineerd. Start verwerking kolomopbouw. 
Er zijn eerdere resultaten aangetroffen vanuit deze configuratie (configuratie_test.xlsx), maar de instellingen waren niet identiek. Berekening wordt opnieuw uitgevoerd.
Variabele woonsituatie_1 wordt uitgevoerd over 14 kolommen.
[DEBUG] Variabele woonsituatie_1 wordt uitgevoerd op subset GGDregio met niveau 17 (GGD Rotterdam-Rijnmond) 
[DEBUG] Subset 1: dataset 1, subset GGDregio, jaar 2024, crossing AGETS414 
[DEBUG] Subset 2: dataset 1, subset GGDregio, jaar 2024, crossing AGGSA402 
[DEBUG] Subset 3: dataset 1, subset GGDregio, jaar 2024, crossing AGLFA401 
[DEBUG] Subset 4: dataset 1, subset GGDregio, jaar 2024, crossing opleidingU 
[DEBUG] Subset 5: dataset 1, subset GGDregio, jaar 2024, crossing NA 
**Error in if (!is.na(col.design$subset[colgroups$test.col[i]])) { : 
  argument is of length zero
Called from: GetTableRow(var, design, kolom_opbouw, subsetmatches)**

Mijn kennis van R is zeer beperkt, dus ik weet niet zo goed waar de error op slaat.
Zou je me kunnen helpen?

Groeten, Nathalie

**Comment by HenkBroekhuizen** [comment]
@NathalieKoene zou je eens nadat de fout is opgetreden _traceback()_ kunnen runnen? Dan kan je zien waar de fout optreedt. En zou je een screenshot oid kunnen delen van je "onderdelen" sheet in de configuratie Excel? Ik heb het idee dat het daar ergens in zit.

**Comment by NathalieKoene** [comment]
[configuratie_test2.xlsx](https://github.com/user-attachments/files/18195839/configuratie_test2.xlsx)

Hoi Henk,

ik heb mijn configuratiebestand toegevoegd als bijlage.
De traceback levert onderstaande stuk op

function (var, design, col.design, subsetmatches) {
  msg("Variabele %s wordt uitgevoerd over %d kolommen.", var, nrow(col.design), level=MSG)
    results = data.frame()
    col.design = col.design %>% group_by(dataset, subset, year, crossing, test.col)
colgroups = group_keys(col.design)
    # splitsen op subset?
  if (!is.null(subsetmatches)) {
    leadingsubset = colnames(subsetmatches)[1]
    leadingcol = min(col.design$col.index[which(col.design$subset == leadingsubset & is.na(col.design$crossing))])
    subsetvals = subsetmatches[,1]
    # kolommen met subset en zonder subset worden apart doorlopen om dubbele calls te voorkomen
    # (anders zou voor ieder niveau in de subset totaalkolommen van andere datasets opnieuw berekend worden - zonde)
    for (s in 1:length(subsetvals)) {
      # bestaat hier data voor?
      if (!(paste0("dummy._col", leadingcol, ".s.", unname(subsetvals[s])) %in% names(design$variables))
          next
       msg("Variabele %s wordt uitgevoerd op subset %s met niveau %s (%s)", var, leadingsubset, as.character(unname(subsetvals[s])), names(subsetvals)[s], level=DEBUG)
       for (i in 1:nrow(colgroups)) {
        if (is.na(colgroups$subset[i])) next
        msg("Subset %d: dataset %d, subset %s, jaar %s, crossing %s", level=DEBUG,
           i, colgroups$dataset[i], colgroups$subset[i], colgroups$year[i], colgroups$crossing[i])

Hopelijk lukt het jou zo de fout te achterhalen.
Alvast bedankt voor je hulp!

groeten, Nathalie

**Comment by aartdijkstra** [comment]
Ik gok dat de naam van de dataset het probleem is. Bij onderdelen heb je in de kolom dataset 'NL' staan, maar bij sign_totaal in de rij erboven 'NL totaal'. Als je die gelijk trekt komt 't waarschijnlijk weer goed. Ik zal ook even een check inbouwen dat 'ie een waarschuwing geeft als de namen niet overeenkomen.

**Comment by NathalieKoene** [comment]
Ja dat was 'm! Thanks! Ik had inderdaad de Nl totaal aangepast, maar dus niet daar
