### ISSUE TITLE
Henks notities over tbl_maken en tbl_GetTableRow

### ISSUE THREAD

**Issue by HenkBroekhuizen** [ggdatascience/GGData_tabellenboek#7]
==tbl_maken==
ll48-51: opties naar configuratie Excel
algemeen: spaties om =?
ll59-60: geef bericht aan gebruiker over dir.create
ll75: wat als er duplicates zijn of NA? moeten we daar wat mee?
ll79: stop?
ll89: waar is de .sav dan toegevoegd?
ll96: ik zou niet itereren over c aangezien dat ook een functie is
ll142: ik heb hier soms ruzie mee omdat de tibble uit haven anders is, dan wil 'ie data[[...]]
ll152: ?? waarom dan rename?
ll157: waar wordt nu precies aangegeven welke vars dummies moeten krijgen?
ll164: denk dat base::dummy sneller is
ll177: overschrijft dit niet wat je in ll175 doet?
ll200: stop?

==tbl_GetTableRow==
ll12: doel snap ik zo snel niet
ll48: voorstel om argumenten met defaults achteraan te zetten
ll93: volgens mij kan dit ook met soortgelijke code, dan krijg je meteen confidence intervals ed:

> svyby( # TODO kijk of je svyby in 1X kan doen voor svytotal en svyciprop
>         formula = as.formula(paste0("~(", paste0(formulas.in, collapse = "+"), ")")),
>         by = list(data.in[, crossvars[i]]),
>         design = survey.design,
>         FUN = svytotal,
>         vartype = 'ci',
>         method = 'xlogit',
>         na.rm = TRUE,
>         na.rm.all = TRUE
>       )

ll123: idem
ll175: moet dit niet andersom? waarom next als is.na?
ll189 idem als ll123

**Comment by aartdijkstra** [comment]
Ik heb de punten die ik **niet** benoem verwerkt in de code.

> ll152: ?? waarom dan rename?
Scheelt later flink typen. data$var is een stuk fijner werken dan data.combined$var.
> ll157: waar wordt nu precies aangegeven welke vars dummies moeten krijgen?
Nergens. Alles wat in de variabelelijst en labels heeft krijgt dummies. Ik zie niet echt een reden om daar een extra lijst voor te maken, dat is alleen maar extra werk.
> ll164: denk dat base::dummy sneller is
Die ken ik niet... ?dummy geeft ook niks.

> ll93: volgens mij kan dit ook met soortgelijke code, dan krijg je meteen confidence intervals ed:
Ik zit hier nu even over te twijfelen... De werking van svyciprop is flink anders; daar moet je I(var==waarde) doen voor ieder antwoord en de kolomsplitsing handmatig uitvoeren. Dat betekent bij een vraag met n calls voor n antwoorden, dus de doorlooptijd explodeert. Daarbij gebruiken we de CI's eigenlijk helemaal niet meer, omdat svychisq het harde werk doet... Is het überhaupt nog zinvol om de CI's te implementeren?
> ll175: moet dit niet andersom? waarom next als is.na?
Daar willen we juist alle rijen die **wel** NA hebben, dus is.na moet TRUE zijn. next 'spoelt door' naar de volgende waarde in de for, dus bij !is.na() willen we inderdaad next doen.

**Comment by aartdijkstra** [comment]
Ik heb de CI helemaal verwijderd uit GetTableRow(). Mocht het ooit nog nodig blijken, dan kunnen we dat tzt nog toevoegen.
